from persona_chess._version import __version__
from persona_chess.dataset.records import MoveExample
from persona_chess.evaluation.metrics import MoveMatchMetrics
from persona_chess.evaluation.persona_report import PersonaEvaluationReport
from persona_chess.facade import PersonaChess
from persona_chess.model_card import PersonaModelCard, build_model_card
from persona_chess.models.blend import BlendPersonaModel
from persona_chess.models.frequency import FrequencyPersonaModel
from persona_chess.models.opening import OpeningBookPersonaModel
from persona_chess.models.phase import PhasePersonaModel
from persona_chess.models.types import MovePrediction
from persona_chess.neural import (
    DEFAULT_BASE_MODEL,
    AdapterManifest,
    HardwareProfile,
    LoraConfig,
    MixedPrecisionMode,
    ModelDownloadResult,
    ModelRegistry,
    MoveVocabulary,
    NeuralAutoConfig,
    NeuralConfigProfile,
    NeuralRecordsTrainRequest,
    NeuralTrainingConfig,
    NeuralTrainRequest,
    NeuralTrainResult,
    PolicyBatch,
    PolicyEvaluationResult,
    PolicySample,
    PositionTokenizer,
    PositionVocabulary,
    RemoteModel,
    TorchRuntimeInfo,
    TrainingEpochResult,
    TrainingProgressUpdate,
    TransformerPolicyConfig,
    cuda_diagnostic_message,
    detect_hardware_profile,
    download_hf_base_model,
    download_remote_model,
    ensure_hf_base_model_cached,
    evaluate_policy_model,
    load_torch_policy_state,
    load_torch_training_state,
    predict_hf_base_moves,
    recommend_neural_config,
    resolve_model_reference,
    resolve_torch_device,
    torch_runtime_info,
    train_neural_persona,
    train_neural_records,
    verify_hf_base_model_usable,
    write_pgn_training_records,
)
from persona_chess.pgn.filters import GameFilter
from persona_chess.profile.types import PersonaProfile
from persona_chess.training.records import TrainingRecord, iter_training_records

__all__ = [
    "FrequencyPersonaModel",
    "BlendPersonaModel",
    "GameFilter",
    "HardwareProfile",
    "MoveExample",
    "MoveMatchMetrics",
    "MovePrediction",
    "MoveVocabulary",
    "ModelDownloadResult",
    "ModelRegistry",
    "AdapterManifest",
    "DEFAULT_BASE_MODEL",
    "LoraConfig",
    "MixedPrecisionMode",
    "NeuralAutoConfig",
    "NeuralConfigProfile",
    "NeuralRecordsTrainRequest",
    "NeuralTrainRequest",
    "NeuralTrainResult",
    "NeuralTrainingConfig",
    "PolicyBatch",
    "PolicyEvaluationResult",
    "PolicySample",
    "OpeningBookPersonaModel",
    "PersonaChess",
    "PersonaEvaluationReport",
    "PersonaModelCard",
    "PersonaProfile",
    "PhasePersonaModel",
    "PositionTokenizer",
    "PositionVocabulary",
    "RemoteModel",
    "TorchRuntimeInfo",
    "TrainingEpochResult",
    "TrainingProgressUpdate",
    "TransformerPolicyConfig",
    "TrainingRecord",
    "__version__",
    "build_model_card",
    "cuda_diagnostic_message",
    "detect_hardware_profile",
    "download_hf_base_model",
    "download_remote_model",
    "ensure_hf_base_model_cached",
    "verify_hf_base_model_usable",
    "evaluate_policy_model",
    "iter_training_records",
    "load_torch_policy_state",
    "load_torch_training_state",
    "recommend_neural_config",
    "predict_hf_base_moves",
    "resolve_model_reference",
    "resolve_torch_device",
    "train_neural_persona",
    "train_neural_records",
    "torch_runtime_info",
    "write_pgn_training_records",
]
